CU-86a0dh4cp - ClickClock: setup do urql e codegen para requests ao g…
simplitech/click-clock pull request #29
Opened 2023-08-15 22:46 UTC by raulduartep

…raphql

2023-08-15 22:46 UTC, melanke commented
Task linked: [CU-86a0dh4cp ClickClock: setup do urql e codegen para requests ao graphql](https://app.clickup.com/t/86a0dh4cp)

2023-08-16 18:06 UTC, melanke requested changes

2023-08-16 18:06 UTC, melanke commented on src/renderer/src/graphql/operations/Users.ts
> +`
Vc testou chamar o método gerado disso aqui no svelte? Pode escrever em algum lugar do projeto um exemplo de como faz?

2023-08-16 18:07 UTC, raulduartep commented on src/renderer/src/graphql/operations/Users.ts
> +`
Testei. Coloco o exemplo onde ? Precisa estar dentro de um componente svelte

2023-08-16 20:07 UTC, merged