CU-86a0haj1h - ClickClock: Melhorar msg de erro quando não tem acesso…
simplitech/click-clock pull request #33
Opened 2023-08-23 22:57 UTC by yumiuehara

… a tarefa no ClickClock

2023-08-23 22:58 UTC, melanke commented
Task linked: [CU-86a0haj1h ClickClock: Melhorar msg de erro quando não tem acesso a tarefa no ClickClock](https://app.clickup.com/t/86a0haj1h)

2023-08-24 13:56 UTC, melanke requested changes

2023-08-24 13:56 UTC, melanke commented on src/renderer/src/App.svelte
> +            showToast(`You don't have access to Clickup Task: #${id}\n Skipping...`, 'red')
Não entendi pq esse código...

2023-08-24 13:56 UTC, melanke commented on src/renderer/src/axiosConfig.ts
> +      // pass
Não tá aqui

2023-08-24 17:46 UTC, yumiuehara commented on src/renderer/src/axiosConfig.ts
> +      // pass
achei que não dava pra pegar o id por aqui, mas dava sim my bad

2023-08-24 20:01 UTC, merged